[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend && python3 -m ensurepip && python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3 -m gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${PORT:-8000}"
